ClassroomHub/ViewModels/ActivityViewModels/StudentAreaViewModel.cs
using System;
using System.Collections.Generic;

namespace ClassroomHub.Web.ViewModels.ActivityViewModels
{
    public class StudentAreaViewModel
    {
        public string ModuleName { get; set; }
        public Guid StudentId { get; set; }
        public List<ActivityViewModel> Activities { get; set; }
    }
}

ClassroomHub/Controllers/ActivityController.cs
using AutoMapper;
using ClassroomHub.Core.Contracts.Services;
using ClassroomHub.Core.Entities;
using ClassroomHub.Web.ViewModels;
using ClassroomHub.Web.ViewModels.ActivityViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace ClassroomHub.Web.Controllers
{
    public class ActivityController : Controller
    {
        private readonly IActivityService _activityService;
        private readonly ITeacherService _teacherService;
        private readonly IStudentService _studentService;
        private readonly IModuleService _moduleService;
        private readonly IDeliveryService _deliveryService;
        private readonly IMapper _mapper;

        public ActivityController(
            IActivityService activityService,
            ITeacherService teacherService,
            IStudentService studentService,
            IModuleService moduleService,
            IDeliveryService deliveryService,
            IMapper mapper)
        {
            _activityService = activityService;
            _teacherService = teacherService;
            _studentService = studentService;
            _moduleService = moduleService;
            _deliveryService = deliveryService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var teachers = _teacherService.GetAll();
            var students = _studentService.GetAll();
            ViewBag.Students = new SelectList(students, "Id", "Name");
            ViewBag.Teachers = new SelectList(teachers, "Id", "Name");
            return View(new ActivityIndexModel());
        }

        public IActionResult TeacherArea(Guid teacherId)
        {
            var modules = _moduleService.GetModulesByTeacherId(teacherId);
            var activities = _mapper.Map<List<ActivityViewModel>>( _activityService.GetAllWithModules(teacherId));            
            ViewBag.Modules = new SelectList(modules,"Id","Nome");            
            return View(activities);
        }

        public IActionResult Create(ActivityViewModel activityViewModel)
        {
            _activityService.Add(_mapper.Map<Activity>(activityViewModel));
            return RedirectToAction("TeacherArea");
        }
        
        public IActionResult GetDeliveries(Guid teacherId)
        {
            var deliveries = _moduleService.GetDeliveredActivitiesByTeacherId(teacherId);
            var deliveryViewModel = _mapper.Map<IEnumerable<DeliveryToTeacherViewModel>>(deliveries);
            return View(deliveryViewModel);
        }

        public IActionResult UpdateDelivery(DeliveryViewModel deliveryViewModel)
        {
            return RedirectToAction(nameof(GetDeliveries), new { deliveryViewModel });
        }

        public IActionResult StudentArea(Guid studentId)
        {
            var student = _studentService.GetFullObjectById(studentId);
            var studentAreaViewModel = _mapper.Map<IEnumerable<StudentAreaViewModel>>(student.Class.Modules);
            foreach (var item in studentAreaViewModel)
            {
                item.StudentId = studentId;
            }

            return View(studentAreaViewModel);
        }

        public IActionResult Details(Guid studentId, Guid ActivityId)
        {            
            var activity = _activityService.GetById(ActivityId);            
            var activityViewModel = _mapper.Map<ActivityDeltailsViewModel>(activity);
            activityViewModel.StudentId = studentId;
            return View(activityViewModel);
        }

        public IActionResult DeliveryActivity(ActivityDeltailsViewModel activityDetails)
        {
            var delivery = _mapper.Map<Delivery>(activityDetails);
            _deliveryService.Add(delivery);
            return RedirectToAction(nameof(StudentArea), new { activityDetails.StudentId });
        }

    }
}

ClassroomHub/Controllers/ModuleController.cs
using AutoMapper;
using ClassroomHub.Core.Contracts.Services;
using ClassroomHub.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using ClassroomHub.Core.Entities;
using System;

namespace ClassroomHub.Web.Controllers
{
    public class ModuleController : Controller
    {
        private  readonly IModuleService _moduleService;
        private readonly ITeacherService _teacherService;
        private readonly IClassService _classService;
        private readonly IMapper _mapper;

        public ModuleController(IModuleService moduleService, IMapper mapper, ITeacherService teacherService, IClassService classService)
        {
            _moduleService = moduleService;
            _teacherService = teacherService;
            _classService = classService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var teachers = _mapper.Map<IEnumerable<TeacherViewModel>>(_teacherService.GetAll());
            var classes = _mapper.Map<IEnumerable<ClassViewModel>>(_classService.GetAll());
            ViewBag.Teachers = new SelectList(teachers, "Id", "Name");
            ViewBag.Classes = new SelectList(classes, "Id", "Name");
            var modules = _moduleService.GetAll();
            var modulesViewModels = _mapper.Map<IEnumerable<ModuleViewModel>>(modules);
            return View(modulesViewModels);
        }

        public IActionResult Create(ModuleViewModel model)
        {
            var module = _mapper.Map<Module>(model);
            _moduleService.Add(module);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(Guid id)
        {
            var module = _mapper.Map<ModuleViewModel>(_moduleService.GetById(id));
            return View(module);
        }
    }
}

ClassroomHub/Views/Activity/Details.cshtml
@using ClassroomHub.Web.ViewModels.ActivityViewModels
@model ActivityDeltailsViewModel

<form method="post" asp-action="DeliveryActivity">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">@Model.Title</h5>
        </div>
        <div class="card-body form-group">
            @Html.TextBoxFor(x => x.ActivityId, new{type="hidden", value=@Model.ActivityId, @readonly=true})
            @Html.TextBoxFor(x => x.StudentId, new{type="hidden", value=@Model.StudentId, @readonly=true})
            @Html.DisplayNameFor(x => x.Description)
            @Html.TextAreaFor(x => x.Description, new{ @class="form-control" , @readonly=true})
            <div class="row mt-2">
                <div class="col-6">
                    @Html.DisplayNameFor(x => x.DueDate)
                    @Html.TextBoxFor(x => x.DueDate, new {@class="form-control", @readonly=true})
                </div>
                <div class="col-6">
                    @Html.DisplayNameFor(x => x.Grade)
                    @Html.TextBoxFor(x => x.Grade, new {@class="form-control", @readonly=true})
                </div>
            </div>
            @Html.DisplayNameFor(x => x.Resolution)
            @Html.TextAreaFor(x => x.Resolution, new {@class="form-control"})
        </div>
        <div class="card-footer">
            <a type="button" asp-action="StudentArea" asp-route-studentId="@Model.StudentId" class="btn btn-secondary">Voltar</a>
            <button class="btn btn-primary" type="submit">Enviar</button>
        </div>
    </div>
</form>

ClassroomHub/Views/Activity/GetDeliveries.cshtml
@using ClassroomHub.Web.ViewModels.ActivityViewModels;
@model IEnumerable<DeliveryToTeacherViewModel>;

<div id="accordion">
    @for (int i = 0; i < Model.Count(); i++)
    {
        var module = Model.ToList()[i];
        var idHeader = "heading" + i;
        var idCollapse = "colapse" + i;
        <div class="card">
            <div class="card-header" id="@idHeader">
                @{
                    var target = "#" + idCollapse;
                }
                <h5>
                    <button class="btn btn-link" data-toggle="collapse" data-target="@target" aria-expanded="false" aria-controls="@idCollapse">
                        @module.Name
                    </button>
                </h5>
            </div>
            <div id="@idCollapse" class="collapse show" aria-labelledby="@idHeader" data-parent="#accordion">
                <div class="card-body">
                    <table class="table table-hover table-striped">
                        <thead>
                            @{
                                var activityHeader = module.Activities.FirstOrDefault();
                            }
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.ActivityScore)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.DueDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var activity in Model.ToList()[i].Activities)
                            {                                
                                <tr>
                                    <td>
                                        @Html.DisplayFor(x => activity.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => activity.ActivityScore)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => activity.DueDate)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
</div>

ClassroomHub/Views/Activity/Index.cshtml
@model ClassroomHub.Web.ViewModels.ActivityViewModels.ActivityIndexModel

<div class="row">
    <div class="col-6">
        <div class="card mt-3">
            <div class="card-header bg-info">
                <h5 class="card-title">Área do professor</h5>
            </div>
            <div class="card-body">
                <form asp-action="TeacherArea" sp-route-id="@Model.TeacherID" class="form-group">
                    @Html.DropDownListFor(x => x.TeacherID, (SelectList)ViewBag.Teachers, "Escolha um professor", new { @class="form-control mb-2"})
                    <button class="btn btn-secondary mt2" type="submit">Enviar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card mt-3">
            <div class="card-header bg-info">
                <h5 class="card-title">Área do aluno</h5>
            </div>
            <div class="card-body">
                <form asp-action="StudentArea" sp-route-id="@Model.StudentID" class="form-group">
                    @Html.DropDownListFor(x => x.StudentID, (SelectList)ViewBag.Students, "Escolha um aluno", new { @class="form-control mb-2"})
                    <button class="btn btn-secondary mt2" type="submit">Enviar</button>
                </form>

            </div>
        </div>
    </div>
</div>

ClassroomHub/Views/Activity/StudentArea.cshtml
@using ClassroomHub.Web.ViewModels.ActivityViewModels
@model IEnumerable<StudentAreaViewModel>


<div id="accordion">
    @for (int i = 0; i < Model.Count(); i++)
    {
        var module = Model.ToList()[i];
        var idHeader = "heading" + i;
        var idCollapse = "colapse" + i;
        <div class="card">
            <div class="card-header" id="@idHeader">
                @{
                    var target = "#" + idCollapse;
                }
                <h5>
                    <button class="btn btn-link" data-toggle="collapse" data-target="@target" aria-expanded="false" aria-controls="@idCollapse">
                        @module.ModuleName
                    </button>
                </h5>
            </div>
            <div id="@idCollapse" class="collapse show" aria-labelledby="@idHeader" data-parent="#accordion">
                <div class="card-body">
                    <table class="table table-hover table-striped">
                        <thead>
                            @{
                                var activityHeader = module.Activities.FirstOrDefault();
                            }
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.ActivityScore)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(x => activityHeader.DueDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var activity in Model.ToList()[i].Activities)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(x => activity.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => activity.ActivityScore)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(x => activity.DueDate)
                                    </td>
                                    <td>
                                        <a type="button"  asp-action="Details" asp-controller="Activity" asp-route-studentId="@module.StudentId" asp-route-activityId="@activity.Id"><i class="fa fa-regular fa-clipboard"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
</div>

ClassroomHub/Views/Activity/TeacherArea.cshtml
@using ClassroomHub.Web.ViewModels.ActivityViewModels
@model IEnumerable<ActivityViewModel>
@{
    Guid moduleId = Guid.Empty;
}

<div class="row">
    <button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#createActivity">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </button>
    <a type="button" class="btn btn-primary ml-2 " asp-action="GetDeliveries" asp-route-teacherId="@Model.First().TeacherId">Atividades Entregues</a>
</div>


<table class="table table-hover table-striped text-center">
    <thead>
        <tr class="success">
            <th>
                @Html.DisplayNameFor(x => x.Title)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.ModuleName)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(x => x.ActivityScore)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var activity in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor( x => activity.Title)
                </td>
                <td>
                    @Html.DisplayFor(x => activity.ModuleName)
                </td>
                <td>
                    @Html.DisplayFor(x => activity.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(x => activity.ActivityScore)
                </td>
            </tr>
        }
    </tbody>
</table>


<partial name="_create" model="new ActivityViewModel()" />

ClassroomHub/Views/Activity/_avaliateDelivery.cshtml
@using ClassroomHub.Web.ViewModels
@model DeliveryViewModel

<div class="modal fade" id="@Model.Id" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-action="UpdateDelivery">
                <div class="modal-header">
                    <h5 class="modal-title">Avaliação</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body form-group">
                    @Html.TextBoxFor(x => x.StudentId, new{type="hidden", value=@Model.StudentId, @readonly=true})
                    @Html.DisplayNameFor(x => x.Description)
                    @Html.TextAreaFor(x => x.Description, new{ @class="form-control" , @readonly=true})
                    <div class="row mt-2">
                        <div class="col-6">
                            @Html.DisplayNameFor(x => x.DeliveyDate)
                            @Html.TextBoxFor(x => x.DeliveyDate, new {@class="form-control", @readonly=true})
                        </div>
                        <div class="col-6">
                            @Html.DisplayNameFor(x => x.Grade)
                            @Html.TextBoxFor(x => x.Grade, new {@class="form-control"} )
                        </div>
                    </div>
                    @Html.DisplayNameFor(x => x.Resolution)
                    @Html.TextAreaFor(x => x.Resolution, new {@class="form-control", @readonly=true})
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" typeof="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

ClassroomHub/Views/Activity/_create.cshtml
@using ClassroomHub.Web.ViewModels.ActivityViewModels
@model ActivityViewModel

<form method="post" asp-controller="Activity" asp-action="Create">
    <div class="modal fade" id="createActivity" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header bg-success">
                    <h5 class="modal-title text-white">Cadastrar Atividade</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                @{
                    var modules = (SelectList)ViewBag.Modules;
                    if (!modules.Any())
                    {
                        <div class="modal-body">
                            <span class="text-danger">Não é possível cadastrar novas atividades sem um modulo registrado.</span>
                            <a type="button" asp-controller="Module" asp-action="Index" class="btn btn-primary mt-2">Cadastrar Curso</a>
                        </div>
                    }
                    else
                    {
                        <div class="modal-body">
                            <div class="row mt-3">
                                <div class="col-12">
                                    @Html.DropDownListFor(x => x.ModuleId,modules, "Selecione um modulo", new {@class="form-control mt-2"})
                                    <span asp-validation-for="ModuleId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    @Html.DisplayNameFor(x => x.Title)
                                    @Html.TextBoxFor(x => x.Title, new{ Placeholder="Nome da atividade", Attribute="width:100%", @class="form-control mt-2"})
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    @Html.DisplayNameFor(x => x.Description)
                                    @Html.TextAreaFor(x => x.Description, new {Placeholder = "Inicio" ,Type="Date", @class="form-control mt-2" })
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-6">
                                    @Html.DisplayNameFor(x => x.DueDate)
                                    @Html.TextBoxFor(x => x.DueDate, new {Placeholder = "Conclusão", Type="Date", @class="form-control mt-2"})
                                    <span asp-validation-for="DueDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-12">
                                    @Html.DisplayNameFor(x =>x.ActivityScore)
                                    @Html.TextBoxFor(x => x.ActivityScore, new {@class="form-control", Type="Number"})
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</form>