ClassroomHub/Controllers/ClassController.cs
using AutoMapper;
using ClassroomHub.Core.Contracts.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using ClassroomHub.Web.ViewModels;
using ClassroomHub.Core.Entities;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using ClassroomHub.Web.Models;
using ClassroomHub.Core.ApplicationExeception;

namespace ClassroomHub.Web.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassService _classService;
        private readonly ICourseService _courseService;
        private readonly IMapper _mapper;

        public ClassController(IClassService classService, IMapper mapper, ICourseService courseService)
        {
            _classService = classService;
            _mapper = mapper;
            _courseService = courseService;
        }

        public IActionResult Index()
        {
            var courses = _mapper.Map<List<CourseViewModel>>(_courseService.GetAll());
            ViewBag.Courses = new SelectList(courses, "Id", "Name");
            return View(new List<ClassViewModel>());
        }

        [HttpPost]
        public IActionResult Index(Guid id)
        {
            var courses = _mapper.Map<List<CourseViewModel>>(_courseService.GetAll());
            ViewBag.Courses = new SelectList(courses, "Id", "Name");
            var classes = _classService.GetAllByCourseId(id);
            var classesViewModel = _mapper.Map<IEnumerable<ClassViewModel>>(classes);
            return View(classesViewModel);
        }

        public IActionResult Create(ClassViewModel model)
        {
            try
            {
                var classEntity = _mapper.Map<Class>(model);
                _classService.Add(classEntity);
                return RedirectToAction(nameof(Index));

            }
            catch (InvalidDateExeception e)
            {
                return RedirectToAction(nameof(Error), new { message = e.Message });
            }
        }

        [HttpGet]
        public IActionResult Update(Guid id)
        {
            var model = _mapper.Map<ClassViewModel>(_classService.GetById(id));
            var courses = _courseService.GetAll();
            ViewBag.Courses = new SelectList(courses, "Id", "Name");
            return View(model);
        }

        public IActionResult Update(ClassViewModel model)
        {
            var entity = _mapper.Map<Class>(model);
            _classService.Update(entity);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(Guid id)
        {
            _classService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error(string message)
        {
            var errorViewModel = new ErrorViewModel() { Message = message };
            return View(errorViewModel);
        }
    }
}

ClassroomHub/Controllers/CourseController.cs
using AutoMapper;
using ClassroomHub.Core.Contracts.Services;
using ClassroomHub.Core.Entities;
using ClassroomHub.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ClassroomHub.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IMapper _mapper;

        public CourseController(ICourseService courseService, IMapper mapper)
        {
            _courseService = courseService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var entityCourses = _courseService.GetAll().ToList();
            var courses = _mapper.Map<List<CourseViewModel>>(entityCourses);
            return View(courses);
        }

        [HttpPost]
        public IActionResult Create(CourseViewModel model)
        {
            _courseService.Add(_mapper.Map<Course>(model));
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var course = _courseService.GetById(id);
            var courseViewModel = _mapper.Map<CourseViewModel>(course);
            return View(courseViewModel);
        }

        [HttpPost]
        public IActionResult Edit(CourseViewModel model)
        {
            var courseEntity = _mapper.Map<Course>(model);
            _courseService.Update(courseEntity);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(Guid id)
        {
            _courseService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ClassroomHub/Controllers/ModuleController.cs
using AutoMapper;
using ClassroomHub.Core.Contracts.Services;
using ClassroomHub.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using ClassroomHub.Core.Entities;
using System;

namespace ClassroomHub.Web.Controllers
{
    public class ModuleController : Controller
    {
        private  readonly IModuleService _moduleService;
        private readonly ITeacherService _teacherService;
        private readonly IClassService _classService;
        private readonly IMapper _mapper;

        public ModuleController(IModuleService moduleService, IMapper mapper, ITeacherService teacherService, IClassService classService)
        {
            _moduleService = moduleService;
            _teacherService = teacherService;
            _classService = classService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var teachers = _mapper.Map<IEnumerable<TeacherViewModel>>(_teacherService.GetAll());
            var classes = _mapper.Map<IEnumerable<ClassViewModel>>(_classService.GetAll());
            ViewBag.Teachers = new SelectList(teachers, "Id", "Name");
            ViewBag.Classes = new SelectList(classes, "Id", "Name");
            var modules = _moduleService.GetAll();
            var modulesViewModels = _mapper.Map<IEnumerable<ModuleViewModel>>(modules);
            return View(modulesViewModels);
        }

        public IActionResult Create(ModuleViewModel model)
        {
            var module = _mapper.Map<Module>(model);
            _moduleService.Add(module);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(Guid id)
        {
            var module = _mapper.Map<ModuleViewModel>(_moduleService.GetById(id));
            return View(module);
        }
    }
}

ClassroomHub/Controllers/UserController.cs
using ClassroomHub.Core.Entities;
using ClassroomHub.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using System.Collections.Generic;
using ClassroomHub.Core.Contracts.Services;
using System;

namespace ClassroomHub.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IMapper mapper)
        {
            _mapper = mapper;
            _userService = userService;
        }
        public IActionResult Index()
        {
            var users = _userService.GetAll();
            var userViewModel = _mapper.Map<List<UserViewModel>>(users); 
            return View(userViewModel);            
        }

        public IActionResult Create(UserViewModel model)
        {
            var user = _mapper.Map<User>(model);
            _userService.Create(user);

            if (model.IsTeacher)
            {
                return RedirectToAction(nameof(Index), "Teacher");
            }
            return RedirectToAction(nameof(Index),"Student");
        }

        [HttpGet]
        public IActionResult Update(Guid id)
        {
            var model = _mapper.Map<UserViewModel>(_userService.GetById(id));
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(UserViewModel model) 
        {
            _userService.Update(_mapper.Map<User>(model));
            return RedirectToAction(nameof(Index));
        }
    }
}

ClassroomHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassroomHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClassroomHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="usersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true">
                              Usuários
                            </a>                            
                            <div class="dropdown-menu" aria-labelledby="usersDropdown">
                              <a class="dropdown-item text-dark" asp-controller="User" asp-action="Index">Usuários</a>
                              <a class="dropdown-item text-darl" asp-controller="Teacher" asp-action="Index">Professores</a>
                              <a class="dropdown-item text-dark" asp-controller="Student" asp-action="Index">Alunos</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Activity" asp-action="Index">Atividades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Course" asp-action="Index">Cursos</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Class" asp-action="Index">Turmas</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Module" asp-action="Index">Modulos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ClassroomHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>